---
- name: deploy graylog
  docker_service:
    project_name: logging
    definition:
      version: '2'
      services:
        mongo:
          image: "mongo:3"
        elasticsearch:
          image: "elasticsearch:2"
          command: "elasticsearch -Des.cluster.name='graylog'"
        graylog:
          image: graylog2/server:2.2.2-1
          environment:
            GRAYLOG_PASSWORD_SECRET: somepasswordpepper
            GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            GRAYLOG_WEB_ENDPOINT_URI: "http://{{ hostvars[inventory_hostname]['public_ip'] }}:9000/api"
          depends_on:
            - mongo
            - elasticsearch
          ports:
            - "9000:9000"
            - "12201:12201/udp"
