---
- name: Check HAProxy
  stat: path=/etc/haproxy
  register: haproxy_dir

- name: Setup HAProxy script
  template: src=haproxy_reload.sh.j2 dest="{{ haproxy_script_location }}/haproxy_reload.sh"
    owner="root" group="root" mode=755
  when: haproxy_dir.stat.exists

- name: Setup cron job for HAProxy
  cron: name="reload marathon haproxy" minute="*/1" job="{{ haproxy_script_location }}/haproxy_reload.sh"
  when: haproxy_dir.stat.exists
