version: "3.1"

services:
  registry:
    image: registry:2.5.1
    deploy:
      replicas: 1
      labels:
        - "traefik.port=5000"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:registry.swarm.uo.techx.fr"
    volumes:
      - registry_volume:/var/lib/registry
    networks:
      - default
      - traefik-net
    environment:
      REGISTRY_LOG_LEVEL: warn
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_HTTP_SECRET: 10C261BB-7D73-4CDD-84AE-DF7620BCEF04
  jenkins:
    image: xebiafrance/uo-jenkins-swarm
    deploy:
      replicas: 1
      labels:
        - "traefik.port=8080"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:jenkins.swarm.uo.techx.fr"
    volumes:
      - jenkins_volume:/var/jenkins_home
    networks:
      - default
      - traefik-net
  jenkins-slave:
    image: xebiafrance/uo-jenkins-slave-swarm
    secrets:
      - jenkins_admin_password
    deploy:
      replicas: 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

secrets:
  jenkins_admin_password:
    external: true

volumes:
  registry_volume:
    driver: rexray/ebs:latest
  jenkins_volume:
    driver: rexray/ebs:latest

networks:
  default:
  traefik-net:
    external: true
