---
- name: "Post-upgrade | etcd3 upgrade | purge etcd2 k8s data"
  command: "{{ bin_dir }}/etcdctl --endpoints={{ etcd_access_addresses }} rm -r /registry"
  environment:
    ETCDCTL_API: 2
  when: kube_apiserver_storage_backend == "etcd3" and  needs_etcd_migration|bool|default(false)
