apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins
    dns: route53
  namespace: ci
  annotations:
      domainName: "jenkins.k8s.uo.techx.fr"
spec:
  selector:
    app: jenkins
  ports:
    - port: 80
      targetPort: 8080
  type: "LoadBalancer"

---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  namespace: ci
  name: jenkins-vol-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "std"
spec:
  "accessModes":
   - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deploy
  namespace: ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
      - name: jenkins
        image: jenkins:2.32.3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-data
        securityContext:
          runAsUser: 1000

      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-vol-claim
