apiVersion: v1
kind: Service
metadata:
  name: registry-service
  labels:
    app: registry
  namespace: ci
spec:
  ports:
    # the port that this service should serve on
  - port: 5000
    targetPort: 5000
  selector:
    app: registry
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  namespace: ci
  name: registry-vol-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "std"
spec:
  "accessModes":
   - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry-deploy
  namespace: ci

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2.5.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
        volumeMounts:
            - mountPath: /var/lib/registry
              name: registry-data
      volumes:
      - name: registry-data
        persistentVolumeClaim:
          claimName: registry-vol-claim
