grafana_image: grafana/grafana
grafana_port: 3000
grafana_admin_password: secret
grafana_service_name: grafana
grafana_url: "http://localhost:{{ grafana_port }}"
grafana_curl: "curl -H 'Content-Type{{ ':' }} application/json' {{ grafana_url}}"