version: "3"

services:
  web:
    image: xebiafrance/uo-click-count
    depends_on:
      - redis
    ports:
      - "80:8080"
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - data-volume:/data

volumes:
  data-volume: