node("maven3") {
    def mvnHome
    def shortCommit

    stage('Preparation') {
        mvnHome = tool 'M3'
        sh 'git rev-parse HEAD > GIT_COMMIT'
        shortCommit = readFile('GIT_COMMIT').take(6)
    }
    stage('Build') {
        dir('applications/click-count') {
            sh "'${mvnHome}/bin/mvn' clean package"
        }
    }
    stage('Results') {
        dir('applications/click-count') {
            archive 'target/clickCount.war'
        }
    }
    stage('Build image') {
        dir('applications/click-count') {
            sh "docker build -t registry.mesos.uo.techx.fr/xebiafrance/click-count:${shortCommit} ."
        }
    }
    stage('Push image') {
        dir('applications/click-count') {
            sh "docker push registry.mesos.uo.techx.fr/xebiafrance/click-count:${shortCommit}"
        }
    }
    stage('Deploy on Staging') {
        dir('applications/click-count') {
            sh "sed -i 's#{{.VERSION}}#${shortCommit}#' marathon.json"
            sh "curl -X PUT -H 'Content-type: application/json' http://mesos-master1.private:8080/v2/groups -d@marathon.json"
        }
    }
}