apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: clickcount-service
  labels:
    app: clickcount
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the clickcount service.
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8080
  selector:
    app: clickcount
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clickcount-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: clickcount
    spec:
      containers:
      - name: clickcount
        image: xebiafrance/uo-click-count
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 8080