---

- name: Node exporter
  hosts: swarm*:kubernetes*:mesos*
  become: true
  vars:
    prometheus_components: [ "node_exporter" ]
  roles:
    - role: 'williamyeh.prometheus'

- name: Prometheus master
  hosts: prometheus
  become: true
  vars:
#    prometheus_components: [ "prometheus" , "alertmanager" ]
    prometheus_port: 9090
    prometheus_exporter_groups:
      - name: node
        hosts: "{{ groups['all'] }}"
        port: 9100
      - name: docker
        hosts: "{{ groups['swarm-master'] + groups['swarm-worker'] }}"
        port: 9101
      - name: mesos
        hosts: "{{ groups['mesos-worker'] }}"
        port: 9110
      - name: 'mesos-master'
        hosts: ['master-exporter.mesosuniv.aws.xebiatechevent.info']
        port: 80

    grafana_port: 3000
    grafana_datasources:
      - name: prometheus
        type: prometheus
        url: "{{ inventory_hostname }}:{{ prometheus_port }}"
    grafana_plugins:
      - natel-discrete-panel
  roles:
    - role: 'docker'
    - { role: 'prometheus', tags: service}
    - { role: "grafana",  tags: service}
    - { role: "graylog",  tags: ['service','wip']}
