---

- hosts: swarm*:kubernetes*:mesos*
  become: true
  vars:
    prometheus_components: [ "node_exporter" ]
  roles:
    - role: 'williamyeh.prometheus'

- hosts: prometheus
  become: true
  vars:
#    prometheus_components: [ "prometheus" , "alertmanager" ]
    prometheus_port: 9099
    grafana_port: 3000
  roles:
    - role: 'docker'
    - role: 'prometheus'
      exporter_groups:
        - name: node
          hosts: "{{ groups['all'] }}"
          port: 9100
        - name: docker
          hosts: "{{ groups['swarm-master'] + groups['swarm-worker'] }}"
          port: 9101
    - role: "grafana"
      grafana_datasources:
        - name: prometheus
          type: prometheus
          url: "{{ inventory_hostname }}:{{ prometheus_port }}"
      grafana_plugins:
        - natel-discrete-panel
#