---
- name: Add apt-key
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com:80 state=present

- name: Add mesosphere repo
  apt_repository: repo='deb http://repos.mesosphere.io/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} main' state=present

- name: Install packages
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - wget
    - curl
    - unzip
    - python
    - python-setuptools
    - python-dev
    - mesos
